// <auto-generated />
using System;
using HexagonalArchitecture.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HexagonalArchitecture.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20211211152751_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HexagonalArchitecture.Domain.Shop.Entity.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("HexagonalArchitecture.Domain.Shop.Entity.Shop", b =>
                {
                    b.OwnsOne("HexagonalArchitecture.Domain.Shop.Entity.ShopCreated", "Created", b1 =>
                        {
                            b1.Property<Guid>("ShopId")
                                .HasColumnType("char(36)");

                            b1.Property<DateTime>("Created")
                                .HasColumnType("Date")
                                .HasColumnName("Created");

                            b1.HasKey("ShopId");

                            b1.ToTable("shops");

                            b1.WithOwner()
                                .HasForeignKey("ShopId");
                        });

                    b.OwnsOne("HexagonalArchitecture.Domain.Shop.Entity.ShopEmail", "Email", b1 =>
                        {
                            b1.Property<Guid>("ShopId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Email");

                            b1.HasKey("ShopId");

                            b1.ToTable("shops");

                            b1.WithOwner()
                                .HasForeignKey("ShopId");
                        });

                    b.OwnsOne("HexagonalArchitecture.Domain.Shop.Entity.ShopName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ShopId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Name");

                            b1.HasKey("ShopId");

                            b1.ToTable("shops");

                            b1.WithOwner()
                                .HasForeignKey("ShopId");
                        });

                    b.Navigation("Created")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
